name: Android CI
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create google-services
        run:
           echo '${{ secrets.GOOGLE_SERVICES_JSON_RELEASE }}' > ./app/google-services.json

      - name: Download Android keystore
        id: android_keystore_dev
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore-dev.jks
          fileDir: '/home/runner/work/DAYO_Android/DAYO_Android/app/android'
          encodedString: ${{ secrets.KEY_STORE_ENCODED }} 

      - name: Create key-dev.properties
        run: |
          echo "storeFile=${{ steps.android_keystore_dev.outputs.filePath }}" > ./app/android/keystore-dev.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> ./app/android/keystore-dev.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> ./app/android/keystore-dev.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> ./app/android/keystore-dev.properties

      - name: Create Properties
        run: |
          echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties
          echo '${{ secrets.SENTRY_PROPERTIES }}' > ./sentry.properties
          echo '${{ secrets.SENTRY_PROPERTIES }}' > ./app/src/main/resources/sentry.properties

      - name: Create android test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Build assemble release apk
        run: ./gradlew assembleRelease
